### PR TITLE
wasm msg gen and signing

### PR DESCRIPTION
**Pull request by asharma13524**
## Motivation

This creates a msg. generation function for clients and programs as well as a `sign_message` function needed for an on-chain multisig style. See comments [here](https://linear.app/puzzlehq/issue/PUZ-262/generate-correct-message-in-dapp-for-leo-token-transfer) for additional details on thought process.

Note: Also included in this pr is a merge of testnet3 from @aleohq/sdk.

Files with wasm changes:
`wasm/src/types.rs`
`wasm/src/account/field.rs`
`wasm/src/account/signature.rs` -> `sign_message`

## Test Plan
1. Clone [this](https://github.com/puzzlehq/leo-sig-verification ) repo -> needed for signature verification
2. Fill in a .env file at the root of the above repo with the private key that you will use. Any will suffice.
3. Pop over to devtools in firenze on this [branch](https://github.com/puzzlehq/firenze/pull/328) (run `rm -rf node_modules && pnpm i && pnpm devtools`
4. Click the sign tab. Input your private key (the same one that is in your `.env` file in the leo-signature-verification repo.
5. Input a message ("place_bid 10u8" or "private_transfer 10u32 aleo1xz0uyudcr24q8nmxr8nlk82penl8jtqyfyuyz6mr5udlt0g3vyfqt895ew '{ owner: aleo1hy0uyudcr24q8nmxr8nlk82penl8jtqyfyuyz6mr5udlt0g3vyfqt9l7ew, amount: 10u128 }'")
6. Copy the fields from the devtools field and place into the inputs file of the leo signature verification [repo]( https://github.com/puzzlehq/leo-sig-verification/blob/main/inputs/signature_verification.in).
7. Copy the signature from devtools field place into the inputs file of the leo signature verification [repo]( into the inputs file of the leo signature verification [repo]( https://github.com/puzzlehq/leo-sig-verification/blob/main/inputs/signature_verification.in).inputs/signature_verification.in).
8. Run `leo clean && leo build && leo run verify_field` inside the root of the leo-signature-verification [repo] (https://github.com/puzzlehq/leo-sig-verification/blob/main)
9. See the ouput `true` to console. 

Screenshot 2023-10-11 at 6 37 59 PM

(Write your test plan here)
Screenshot 2023-10-11 at 6 08 36 PM

## Related PRs

[(Firenze PR)](https://github.com/puzzlehq/firenze/pull/328)

NOTE: I did not update the aleo wasm node js package [here](https://www.npmjs.com/package/@puzzlehq/aleo-wasm-nodejs)

### CODE REVIEW

**Review by lukenewman — APPROVED** [review]
these testing steps work! the linked linear ticket is a bit of a cluster of info -- is there any doc that cleanly outlines the why, what, how of all this?

**Comment by asharma13524** [comment]
> these testing steps work! the linked linear ticket is a bit of a cluster of info -- is there any doc that cleanly outlines the why, what, how of all this?

nope just created https://linear.app/puzzlehq/issue/PUZ-317/document-wasm-message-generation-method to consolidate notes on this.

**Comment by lukenewman** [comment]
this is ready to merge -- thinking of holding off for a sec just until we confirm that the signature verification is tested in-execution

**Comment by asharma13524** [comment]
> this is ready to merge -- thinking of holding off for a sec just until we confirm that the signature verification is tested in-execution

Agreed thinking about this some more I may slightly tweak the message gen to only have 1 field instead of the 4+ fields it's currently generating.

**Comment by lukenewman** [comment]
@asharma13524 is the field-length optimization still an option?

**Pull request merged**
